#ifndef MOVE_ENUM_H
#define MOVE_ENUM_H


enum MoveEnum {
    SHIFT_ADD_MOVE = 0,
    SHIFT_REMOVE_MOVE = 1,
    SHIFT_START_CHANGE_MOVE = 2,
    SHIFT_SWAP_MOVE = 3,
    SHIFT_SWAP_PERIOD_MOVE = 4,
    ACTIVITY_LENGTH_CHANGE_MOVE = 5,
    ACTIVITY_TASK_CHANGE_MOVE = 6,
    ACTIVITY_ADD_MOVE = 7,
    ACTIVITY_REMOVE_MOVE = 8,

    INVALID_MOVE = -1
};


#endif //MOVE_ENUM_H
